# Generated by Django 5.2.16 on 2026-07-15 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Action',
        ),
        migrations.RemoveField(
            model_name='modification',
            name='fichier',
        ),
        migrations.RemoveField(
            model_name='modification',
            name='utilisateur',
        ),
        migrations.RemoveField(
            model_name='fichier',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='fichier',
            name='utilisateur',
        ),
        migrations.RemoveField(
            model_name='fichier',
            name='droits_acces',
        ),
        migrations.RemoveField(
            model_name='fichier',
            name='metadonnees',
        ),
        migrations.AddField(
            model_name='fichier',
            name='proprietaire',
            field=models.CharField(db_index=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='fichier',
            name='date_upload',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='fichier',
            name='fichier_type_mime',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='fichier',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='FichierWorkspace',
        ),
        migrations.DeleteModel(
            name='Modification',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.DeleteModel(
            name='Utilisateur',
        ),
    ]
