# Generated by Django 5.2.16 on 2026-07-15 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_delete_action_remove_modification_fichier_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destinataire', models.CharField(db_index=True, max_length=255)),
                ('date_partage', models.DateTimeField(auto_now_add=True)),
                ('fichier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partages', to='api.fichier')),
            ],
            options={
                'db_table': 'partages',
                'ordering': ['destinataire'],
                'constraints': [models.UniqueConstraint(fields=('fichier', 'destinataire'), name='unique_partage')],
            },
        ),
    ]
