version: "3.9"

networks:
  sso-net:
    external: true
    name: sso-lab_sso-net
  dev-net:
    external: true
    name: dev-net

services:

  backend:
    build: ./backend
    container_name: traitement-de-fichiers-compils-backend
    restart: unless-stopped
    env_file: .env
    ports:
      - "8089:8000"
    networks:
      - sso-net
      - dev-net
    labels:
      caddy: "${DOMAIN}"
      caddy.handle_path: "/traitement-de-fichiers-compils-api/*"
      caddy.handle_path.reverse_proxy: "{{upstreams 8000}}"

  frontend:
    build: ./frontend
    container_name: traitement-de-fichiers-compils-frontend
    restart: unless-stopped
    env_file: .env
    ports:
      - "4207:80"
    networks:
      - sso-net
    labels:
      caddy: "${DOMAIN}"
      caddy.handle_path: "/traitement-de-fichiers-compils/*"
      caddy.handle_path.reverse_proxy: "{{upstreams 80}}"
